[tool.poetry]
name = "db-corsework"
version = "0.1.0"
description = ""
authors = ["slav <vrazumihindima@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
